### ISSUE TITLE
Person. Los atributos firstName y surname no pueden ser some

### ISSUE THREAD

**Issue by estebansota-gnoss** [HerculesCRUE/ROH#5]
Los atributos Nombre y Apellidos  (firstName y surname) no pueden ser "some". Sólo sería "some" el atributo "Nombre" (name), porque en algunos casos nos llega una cadena de texto de la que no sabemos seguro qué es nombre y qué apellidos. Por ejemplo, al cargar un coautor de una publicación que no está en la universidad.

**Comment by brianjlowe** [comment]
I agree, although not specifically because of challenges in loading unstructured data:  we could assert that some first name exists even if we can't yet state what the name is.  The immediate problem I see here is that such an axiom would not actually hold true for all persons in existence, some of whom lack a surname, a given name, or both.

Besides these (firstName some string, surname some string), there are a number of other sibling axioms that redefine a class from another ontology (foaf:Person).  We should either eliminate them or introduce an intermediate roh:Person (less attractive option) that is a subclass of foaf:Person .

**Comment by brianjlowe** [comment]
Resolved with issue #9
